services:
  app:
    container_name: app
    build:
      dockerfile: app.dockerfile
    ports:
      - "${APP_PORT}:8000"
      - "9229:9229"
    env_file:
      - .env
    command: tail -f /dev/null
    volumes:
      - .:/app
    tty: true
